In [26]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cpu


# Introduction to Tensors
## Creating tensors

In [27]:
# Scalar
scalar = torch.scalar_tensor(7, dtype=torch.int)
scalar

tensor(7, dtype=torch.int32)

In [28]:
scalar.ndim

0

In [29]:
scalar.item()

7

In [30]:
# Vector
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [31]:
vector.ndim

1

In [32]:
vector.shape

torch.Size([3])

In [33]:
# MATRIX
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [34]:
MATRIX.ndim

2

In [35]:
MATRIX.shape

torch.Size([2, 2])

In [36]:
# TENSOR
TENSOR = torch.tensor([[[1, 2], 
                        [3, 4], 
                        [5, 6]]])
TENSOR

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [37]:
TENSOR.ndim

3

In [38]:
TENSOR.shape

torch.Size([1, 3, 2])

## Exercises

In [41]:
M1 = torch.tensor([[[1,2,3],[3,12,3]], [[1,2,4],[1,5,2]]])
M1

tensor([[[ 1,  2,  3],
         [ 3, 12,  3]],

        [[ 1,  2,  4],
         [ 1,  5,  2]]])

In [42]:
M1.ndim

3

In [43]:
M1.shape

torch.Size([2, 2, 3])

In [45]:
M2 = torch.tensor([[[[4,4], [5,4]]]])
M2

tensor([[[[4, 4],
          [5, 4]]]])

In [46]:
M2.ndim

4

In [47]:
M2.shape

torch.Size([1, 1, 2, 2])

In [49]:
M3 = torch.tensor([[[1,0,1,0,0,], [1,0,0,1,0]], [[1,0,1,1,1], [0,1,1,1,0]]])
M3

tensor([[[1, 0, 1, 0, 0],
         [1, 0, 0, 1, 0]],

        [[1, 0, 1, 1, 1],
         [0, 1, 1, 1, 0]]])

In [50]:
M3.ndim

3

In [51]:
M3.shape

torch.Size([2, 2, 5])