In [2]:
from random import random

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cpu


# Introduction to Tensors
Tensors are the fundamental building blocks of ML. Their job is to represent data in a numerical way.
## Creating tensors

In [3]:
# Scalar
scalar = torch.scalar_tensor(7, dtype=torch.int)
scalar

tensor(7, dtype=torch.int32)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

In [9]:
# MATRIX
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2], 
                        [3, 4], 
                        [5, 6]]])
TENSOR

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 2])

### Exercises

In [15]:
M1 = torch.tensor([[[1,2,3],[3,12,3]], [[1,2,4],[1,5,2]]])
M1

tensor([[[ 1,  2,  3],
         [ 3, 12,  3]],

        [[ 1,  2,  4],
         [ 1,  5,  2]]])

In [16]:
M1.ndim

3

In [17]:
M1.shape

torch.Size([2, 2, 3])

In [18]:
M2 = torch.tensor([[[[4,4], [5,4]]]])
M2

tensor([[[[4, 4],
          [5, 4]]]])

In [19]:
M2.ndim

4

In [20]:
M2.shape

torch.Size([1, 1, 2, 2])

In [21]:
M3 = torch.tensor([[[1,0,1,0,0,], [1,0,0,1,0]], [[1,0,1,1,1], [0,1,1,1,0]]])
M3

tensor([[[1, 0, 1, 0, 0],
         [1, 0, 0, 1, 0]],

        [[1, 0, 1, 1, 1],
         [0, 1, 1, 1, 0]]])

In [22]:
M3.ndim

3

In [23]:
M3.shape

torch.Size([2, 2, 5])

## Random Tensors
Random tensors are important because of the way many neural networks learn. They start with tensors full of random numbers and then adjust those numbers to better represent the data.

In [24]:
# Create random tensor of size (3, 4)
random_tensor = torch.rand((3, 4))
random_tensor

tensor([[0.5447, 0.3018, 0.0451, 0.4901],
        [0.6963, 0.8644, 0.5035, 0.6964],
        [0.2016, 0.9336, 0.5681, 0.1961]])

In [25]:
random_tensor.ndim

2

In [26]:
random_tensor.shape

torch.Size([3, 4])

In [27]:
# Create random tensor similar to image
random_img_tensor = torch.rand((3, 224, 224))
random_img_tensor.ndim

3

### Exercises

In [28]:
sales_tensor = torch.rand((10, 7))
sales_tensor

tensor([[0.6772, 0.1481, 0.7768, 0.1095, 0.3635, 0.4765, 0.9195],
        [0.4478, 0.0075, 0.5989, 0.1406, 0.5261, 0.1715, 0.7412],
        [0.5932, 0.7223, 0.1732, 0.4040, 0.0291, 0.4278, 0.5679],
        [0.7810, 0.3314, 0.6463, 0.2172, 0.3202, 0.0544, 0.3151],
        [0.4677, 0.1592, 0.8364, 0.2705, 0.0211, 0.7047, 0.7250],
        [0.5730, 0.9793, 0.6317, 0.7518, 0.4647, 0.1786, 0.4240],
        [0.4039, 0.7258, 0.5029, 0.7520, 0.1314, 0.2914, 0.8339],
        [0.5197, 0.4250, 0.9307, 0.2786, 0.1378, 0.6610, 0.4635],
        [0.3048, 0.3859, 0.4860, 0.7139, 0.2533, 0.6627, 0.8649],
        [0.3761, 0.8069, 0.8219, 0.5732, 0.7965, 0.8102, 0.7818]])

In [29]:
personal_numbers_tensor = torch.rand((6, 12))
personal_numbers_tensor

tensor([[0.7424, 0.7377, 0.6499, 0.6261, 0.6766, 0.6453, 0.9819, 0.4202, 0.5070,
         0.9004, 0.4851, 0.0055],
        [0.2425, 0.7912, 0.2210, 0.2240, 0.8347, 0.7223, 0.9619, 0.2778, 0.0774,
         0.7339, 0.9812, 0.5409],
        [0.5320, 0.9273, 0.0239, 0.5260, 0.7554, 0.6852, 0.8440, 0.8200, 0.7871,
         0.3250, 0.7039, 0.7732],
        [0.8063, 0.9995, 0.2079, 0.4633, 0.0081, 0.9473, 0.0964, 0.3101, 0.9992,
         0.6244, 0.9912, 0.7315],
        [0.5765, 0.9595, 0.4073, 0.7061, 0.1427, 0.0360, 0.0084, 0.1274, 0.2336,
         0.9587, 0.0554, 0.9343],
        [0.0403, 0.8524, 0.4046, 0.9304, 0.2973, 0.0859, 0.4431, 0.0151, 0.1433,
         0.5457, 0.3593, 0.4270]])

## Zeros and ones

In [30]:
# Create tensor of all zeros
zeros = torch.zeros((3,5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [31]:
# Create tensor of ones
ones = torch.ones((4,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [32]:
ones.dtype

torch.float32

## Creating range of tensors and tensor-like

In [33]:
# Create range of tensors
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
sm_range = torch.arange(start=10, end=110, step=5)
sm_range

tensor([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,  75,
         80,  85,  90,  95, 100, 105])

In [35]:
# Create tenosr-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
rand_ints = torch.randint_like(input=sm_range, high=255)
rand_ints

tensor([163, 173,  44, 192, 148, 115, 190,  21, 145, 155,  25,  16, 135, 225,
        196, 112, 212,  53, 138,  63])

## Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into ML:
   1. Tensors not right datatype,
   2. Tensors not right shape,
   3. Tensors not on the right device.

In [37]:
float_32_tensor = torch.tensor([3.0, 2.0, 2.4],
                               dtype=None, # What datatype is the tensor (e.g. float32)
                               device=None,
                               requires_grad=False)
float_32_tensor.dtype

torch.float32