In [2]:
from random import random

import torch
import torch.nn as nn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cpu


# Neural Networks
NNs are layers of artificial neurons. Each neuron has its own activation function, weights and biases that are adjusted during training process.

In [4]:
network = nn.Sequential(
    nn.Linear(12, 20),
    nn.ReLU(),
    
    nn.Linear(20, 13),
    nn.ReLU(),
    
    nn.Linear(13, 5),
    nn.ReLU(),
    
    nn.Linear(5, 1),
    nn.ReLU(),
)

## What's a forward pass?
- Input data is **passed forward** or **propagated** through a network;
- Computations performed at each layer;
- Outputs of each layer passed to each subsequent layer;
- **Output** of final layer: "prediction";
- Used for both training and prediction;

In [12]:
input_tensor = torch.tensor([[5,3,2,3,1,4,5,3,2,3,1,4],
                             [5,3,2,3,1,4,8,2,3,0,1,7]], dtype=torch.float)

In [13]:
network.forward(input_tensor)

tensor([[-0.5797],
        [-0.6800]], grad_fn=<AddmmBackward0>)

## Is there also a backward pass?
- **Backward pass** or **backpropagation** is used to update weights and biases during training;
- In the "training loop", we:
    1. **Propagate** data forward;
    2. **Compare** outputs to true values (ground-truth);
    3. **Backpropagate** to update model weights and biases;
    4. **Repeat** until weights and biases are tuned to produce useful outputs;

## Binary classification: forward pass

In [14]:
network = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, 1),
    nn.Sigmoid(),
)

In [17]:
input_data = torch.tensor([
    [-1, -4.5, 42.5, -53.3, 6.03, 2.43],
    [1, -4.5, 12.5, 53.3, 9.03, 1.43],
    [1, 4.5, 42.5, +53.3, 6.03, 2.43],
    [1, 4.5, -42.5, 53.3, 6.03, 7.43],    
])

In [18]:
network.forward(input_data)

tensor([[0.1360],
        [0.9935],
        [0.9994],
        [0.6975]], grad_fn=<SigmoidBackward0>)

## Multi-class classification: forward pass

In [24]:
n_classes = 5
network = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, n_classes),
    nn.Softmax(dim=-1),
)

In [25]:
network.forward(input_data)

tensor([[1.0887e-06, 8.9358e-09, 9.8916e-01, 2.7295e-03, 8.1142e-03],
        [1.1607e-06, 9.9882e-01, 1.8233e-11, 1.1746e-03, 1.5879e-07],
        [2.0167e-08, 9.7988e-01, 2.0351e-13, 2.0123e-02, 3.3075e-08],
        [3.2115e-01, 6.7882e-01, 7.6900e-07, 6.5111e-07, 2.6392e-05]],
       grad_fn=<SoftmaxBackward0>)

# Regression: forward pass

In [26]:
network = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, 1)
)

In [27]:
network.forward(input_data)

tensor([[ 2.5220],
        [ 1.3042],
        [ 3.2861],
        [-3.6118]], grad_fn=<AddmmBackward0>)